Fix gh-action on win: point to libarchive
related to:
https://github.com/conda/conda/issues/12563#issuecomment-1494264704

ci build on windows failing due to problems with libarchive with errors
like

...
  File "...\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable```